server:
  port: 9999
  servlet:
    context-path: /api/v1
#    session:
#      cookie:
#       name: BIUSID
spring:
  profiles:
    active: dev
    include: druid,mybatisplus
  redis:
    host: localhost
    port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: qwer1234
#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: false
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mon4cc.entity